---
title: 十四五规划建议中与生态有关的内容
author: 老王
date: '2020-12-20'
categories:
  - Forest Management
  - 生态学习
---

中国共产党第十九届中央委员会第五次全体会议2020年10月26日至29日在北京举行，审议通过了[《中共中央关于制定国民经济和社会发展第十四个五年规划和二〇三五年远景目标的建议》](https://www.xuexi.cn/lgpage/detail/index.html?id=1182141130175071280&amp;item_id=1182141130175071280)。

每五年一次的规划，是我国制度优越性的一个重要体现，保证了政策的连贯性、前进的方向性，也为全国人民往什么方向发力指明方向。事实证明，下一个阶段国家要做什么都是清清楚楚写给每个人看了，仔细研究，想办法把个人发展和国家需求结合起来，投身一个小小方向，必定能取得更好的结果。

所以，五年规划是一定要认真揣摩的。

今天学习这个《建议》，找找和自己有关的内容做好摘抄并初步思考，指导今后工作学习。

## 1. 结构和主要内容

《建议》分为15个部分，60条。

> 一、全面建成小康社会，开启全面建设社会主义现代化国家新征程    
> 二、“十四五”时期经济社会发展指导方针和主要目标  
> 三、坚持创新驱动发展，全面塑造发展新优势  
> 四、加快发展现代产业体系，推动经济体系优化升级  
> 五、形成强大国内市场，构建新发展格局  
> 六、全面深化改革，构建高水平社会主义市场经济体制  
> 七、优先发展农业农村，全面推进乡村振兴  
> 八、优化国土空间布局，推进区域协调发展和新型城镇化  
> 九、繁荣发展文化事业和文化产业，提高国家文化软实力  
> **十、推动绿色发展，促进人与自然和谐共生**  
> **十一、实行高水平对外开放，开拓合作共赢新局面**  
> 十二、改善人民生活品质，提高社会建设水平  
> 十三、统筹发展和安全，建设更高水平的平安中国  
> 十四、加快国防和军队现代化，实现富国和强军相统一  
> 十五、全党全国各族人民团结起来，为实现“十四五”规划和二〇三五年远景目标而奋斗  

其中与生态有关的论述在第十部分较为集中，与外资有关的论述包含在第十一部分（当然仅为一小部分）。

这十五个部分之间是经典的“总分总”结构，首先第一部分是目标，第二部分是要求；然后三到十四，分别从科技创新、产业体系、做大国内市场、强化社会主义市场经济体制、农村振兴、区域协调发展、文化软实力、绿色生态、对外开放、社会建设、安全发展、国防军队等12个方面阐述；最后第十五部份总结。

总书记对建议稿的说明中指出，

> 十四五”时期经济社会发展要以推动高质量发展为主题……新时代新阶段的发展必须贯彻新发展理念，必须是高质量发展。当前，我国社会主要矛盾已经转化为人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾，发展中的矛盾和问题集中体现在发展质量上。这就要求我们必须把发展质量问题摆在更为突出的位置，着力提升发展质量和效益。

个人理解，高质量是基于新发展理念的，是针对当前社会主要矛盾的，是相对于低质量的。新发展理念下，不再像之前一样，片面追求经济发展，而忽视对供给结构、环境影响、价值导向、文化观念等方面的建设。这些需要改变的领域很多，很难具体概括出来，但只要以人民为中心，就能够提纲挈领地用“高质量、新发展理念”来引导，从而实现不同行业不同领域的发展。

经济发展中心逐渐转移到国内，独立自主正成为更多人的共识，对西方发达国家的幻想逐渐褪去，我们要用自己强大的国内大循环说服他们理性的进入我们的国外循环，绝不能把十四亿人的经济命脉哪怕是部分的依赖国外。我们要加强创新，产业链要理顺了，不能有掐脖子的技术（三、四），还要底线思维，主要靠国内市场完成这个过程（五），在这个过程中提高经济运行水平、着重把乡村也振兴了，因为乡村既是发展重点也是广大的市场（六、七）。当然城市也很重要，但要管的更好更严，而且要和乡村发展统筹起来（八）

在经济发展过程中，文化发展也要跟上。这块之前太拉跨了，比如电影行业，烂片层出不穷，价值观混乱不堪。但新发展理念下，只要坚持用以人民为中心的观念来分析，振奋革命情怀，崇尚英雄主义，以往一些明显垃圾的电影就能很快被扫入垃圾堆，比如郭敬明的系列作品。哪怕伪装的比较深的，也在逃不过人民的火眼金睛，很快被扒下画皮，比如管虎的金岗川。相对的，一些经典革命影片又重新回到年轻人的身边并受到追捧，如高山下的花环、上甘岭等。价值观也在逐渐重塑，王思聪已经很久不敢炫富了，马云也逐渐褪去了光环，经济上的成功逐渐不再是衡量人是否成功的唯一标准，为人民服务、为社会做贡献的风尚逐渐形成。特别是经过疫情的洗礼，集体主义正在重新变的深入人心。（九）

文化之后是环境，经济发展，人要与自然和谐共生，国家也要与世界和谐共生，搞好对外开放（十、十一）；总之大家通力协作，改善人民生活品质，提高社会建设水平（十二）。当然不能只顾着发展，防人之心不可无，不管是内部还是外部，都要防范有人搞破坏（十三、十四）。

全面，太全面了！

## 2. 与生态、环境、自然资源、外资使用等有关的内容

### 一、全面建成小康社会，开启全面建设社会主义现代化国家新征程

#### 2.我国发展环境面临深刻复杂变化。

生态环保任重道远

#### 3.到二〇三五年基本实现社会主义现代化远景目标。

党的十九大对实现第二个百年奋斗目标作出分两个阶段推进的战略安排，即到二〇三五年基本实现社会主义现代化，到本世纪中叶把我国建成富强民主文明和谐美丽的社会主义现代化强国。**碳排放达峰后稳中有降**，生态环境根本好转，美丽中国建设目标基本实现；形成对外开放新格局，参与国际经济合作和竞争新优势明显增强。

### 二、“十四五”时期经济社会发展指导方针和主要目标

#### 4.“十四五”时期经济社会发展指导思想。

坚定不移贯彻创新、协调、绿色、开放、共享的新发展理念

#### 6.“十四五”时期经济社会发展主要目标。

——生态文明建设实现新进步。国土空间开发保护格局得到优化，生产生活方式绿色转型成效显著，能源资源配置更加合理、利用效率大幅提高，主要污染物排放总量持续减少，生态环境持续改善，生态安全屏障更加牢固，城乡人居环境明显改善。

### 三、坚持创新驱动发展，全面塑造发展新优势

#### 7.强化国家战略科技力量。生物育种

### 七、优先发展农业农村，全面推进乡村振兴

#### 25.提高农业质量效益和竞争力。

推动农业供给侧结构性改革，优化农业生产结构和区域布局。发展县域经济，推动农村一二三产业融合发展，丰富乡村经济业态，拓展农民增收空间。

#### 27.深化农村改革。

健全城乡融合发展机制，推动城乡要素平等交换、双向流动，增强农业农村发展活力。落实第二轮土地承包到期后再延长三十年政策，加快培育农民合作社、家庭农场等新型农业经营主体，健全农业专业化社会化服务体系，发展多种形式适度规模经营，实现小农户和现代农业有机衔接。健全城乡统一的建设用地市场，积极探索实施农村集体经营性建设用地入市制度。建立土地征收公共利益用地认定机制，缩小土地征收范围。探索宅基地所有权、资格权、使用权分置实现形式。保障进城落户农民土地承包权、宅基地使用权、集体收益分配权，鼓励依法自愿有偿转让。深化农村集体产权制度改革，发展新型农村集体经济。健全农村金融服务体系，发展农业保险。

### 八、优化国土空间布局，推进区域协调发展和新型城镇化

#### 29.构建国土空间开发保护新格局。

立足资源环境承载能力，发挥各地比较优势，逐步形成**城市化地区、农产品主产区、生态功能区**三大空间格局，优化重大基础设施、重大生产力和公共资源布局。支持城市化地区高效集聚经济和人口、保护基本农田和生态空间，支持农产品主产区增强农业生产能力，支持生态功能区把发展重点放到保护生态环境、**提供生态产品**上，支持生态功能区的人口逐步有序转移，形成主体功能明显、优势互补、高质量发展的国土空间开发保护新格局。

### 十、推动绿色发展，促进人与自然和谐共生

坚持绿水青山就是金山银山理念，坚持**尊重自然、顺应自然、保护自然**，坚持**节约优先、保护优先、自然恢复为主**，守住自然生态安全边界。深入实施可持续发展战略，完善生态文明领域统筹协调机制，构建生态文明体系，促进经济社会发展全面绿色转型，建设人与自然和谐共生的现代化。

#### 35.加快推动绿色低碳发展。

强化国土空间规划和用途管控，落实生态保护、基本农田、城镇开发等空间管控边界，减少人类活动对自然空间的占用。强化绿色发展的法律和政策保障，发展绿色金融，支持绿色技术创新，推进清洁生产，发展环保产业，推进重点行业和重要领域绿色化改造。推动能源清洁低碳安全高效利用。发展绿色建筑。开展绿色生活创建活动。**降低碳排放强度，支持有条件的地方率先达到碳排放峰值，制定二〇三〇年前碳排放达峰行动方案**。

#### 36.持续改善环境质量。

增强全社会生态环保意识，深入打好污染防治攻坚战。继续开展污染防治行动，建立地上地下、陆海统筹的生态环境治理制度。强化多污染物协同控制和区域协同治理，加强细颗粒物和臭氧协同控制，基本消除重污染天气。治理城乡生活环境，推进城镇污水管网全覆盖，基本消除城市黑臭水体。推进化肥农药减量化和土壤污染治理，加强白色污染治理。加强危险废物医疗废物收集处理。完成重点地区危险化学品生产企业搬迁改造。重视新污染物治理。全面实行排污许可制，**推进排污权、用能权、用水权、碳排放权市场化交易**。完善环境保护、节能减排约束性指标管理。完善中央生态环境保护督察制度。积极参与和引领应对气候变化等生态环保国际合作。

#### 37.提升生态系统质量和稳定性。

坚持山水林田湖草系统治理，**构建以国家公园为主体的自然保护地体系**。实施生物多样性保护重大工程。加强外来物种管控。强化河湖长制，加强大江大河和重要湖泊湿地生态保护治理，实施好长江十年禁渔。科学推进荒漠化、石漠化、水土流失综合治理，开展大规模国土绿化行动，推行林长制。推行草原森林河流湖泊休养生息，加强黑土地保护，健全耕地休耕轮作制度。加强全球气候变暖对我国承受力脆弱地区影响的观测，完善自然保护地、生态保护红线监管制度，开展生态系统保护成效监测评估。

#### 38.全面提高资源利用效率。

健全自然资源资产产权制度和法律法规，加强自然资源调查评价监测和确权登记，**建立生态产品价值实现机制，完善市场化、多元化生态补偿**，推进资源总量管理、科学配置、全面节约、循环利用。实施国家节水行动，建立水资源刚性约束制度。提高海洋资源、矿产资源开发保护水平。完善资源价格形成机制。推行垃圾分类和减量化、资源化。加快构建废旧物资循环利用体系。

### 十一、实行高水平对外开放，开拓合作共赢新局面

坚持实施更大范围、更宽领域、更深层次对外开放，依托我国大市场优势，促进国际合作，实现互利共赢。

#### 39.建设更高水平开放型经济新体制。

全面提高对外开放水平，推动贸易和投资自由化便利化，推进贸易创新发展，增强对外贸易综合竞争力。完善外商投资准入前国民待遇加负面清单管理制度，有序扩大服务业对外开放，依法保护外资企业合法权益，健全促进和保障境外投资的法律、政策和服务体系，坚定维护中国企业海外合法权益，实现高质量引进来和高水平走出去。完善自由贸易试验区布局，赋予其更大改革自主权，稳步推进海南自由贸易港建设，建设对外开放新高地。稳慎推进人民币国际化，坚持市场驱动和企业自主选择，营造以人民币自由使用为基础的新型互利合作关系。发挥好中国国际进口博览会等重要展会平台作用。

## 3. 一些想法

在生态领域（包括林业），似乎生态产品价值实现是一个值得深入研究的方向。

首先这个问题可以扎根领域很广。目前细分的行业，如造林、森林经营、水土保持、保护地管理、国家公园建设等，都可以结合这个问题，有深入研究的基础。

其次这个问题有价值。在36部分明确提出，要推进用水权、碳排放市场化交易，要交易就得把水源涵养、森林固碳等生态产品量化计算出来；38部分进一步明确，建立生态产品价值实现机制，完善市场化、多元化生态补偿，因此这个活是有切实社会需求的。

先这些吧，有其他想法再补。
