baseurl = "/"
languageCode = "en-us"
title = "生态学习"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles =  ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "博客"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 2

[params]
    description = "工作、学习、生活随记"
    footer = "&copy; [Wang](https://ecology.wang) 2019 | [Github](https://github.com/ecowang) "
    highlightjsCDN: "//cdn.bootcss.com"
    highlightjsLang: ["r", "yaml", "tex"]
    highlightjsTheme: "github"
    highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true
