---
title: 读《国土空间生态修复亟待把握的几个要点》笔记
author: 老王
date: '2020-12-24'
slug: []
categories:
  - Forest Management
tags:
  - Forest management
---

学习强国上，傅伯杰院士《[国土空间生态修复亟待把握的几个要点](https://article.xuexi.cn/articles/index.html?art_id=16140405072372331769&source=share&study_style_id=feeds_default&share_to=wx_single&study_share_enable=1&study_comment_disable=0&ptype=0&item_id=16140405072372331769&from=groupmessage&isappinstalled=0)》跟当前工作有联系，学习，记笔记。

首先他聊的是“国土空间生态修复”，**国土空间**的定义既不是原来的国土，也不是生态系统，而是“承载人类活动的物质载体，由生态系统与人类社会相互作用形成”，概念给延伸拓展了。然后**生态修复**的概念是“对已退化、损害或彻底破坏的生态系统进行恢复的过程，其修复对象不仅包括生态系统结构和功能，也包括提升生态系统服务”。

看看，什么叫大家，一竿子把山水林田湖草沙海都打进去了，这也直接导致我可以方便的借用其中的概念来写报告，跑不太偏。

造林营林是在搞生态建设，和生态修复有关但不完全一样；生态修复主要来源是国土的矿山修复，天然带着工程的因素。院士这篇文章讲国土空间生态修复，也是从过去“聚焦于水、土等单一生态要素，或水土流失等单一自然过程”展开的，认为那种生态修复过程“导致治标不治本的问题较为突出”，因此要发展一种更加强调系统性、整体性、综合性的国土空间生态修复理念。

这种理念也是在新时代生态文明建设思想的指导下产生的，包括“统筹山水林田湖草系统治理”、“深入实施山水林田湖草一体化生态保护和修复”、“绿水青山就是金山银山”等论断。对国土空间生态修复的理论和方法体系在以下几个方面扩展：

- 生态保护和修复**对象**从自然要素转向社会-生态要素；

- **尺度**从局地生态系统健康改善转向多尺度生态安全格局塑造；

- **目标**从生态系统结构与功能优化转向人类生态福祉提升等。

在这几个角度，提出**应用人地耦合系统理论**阐释国土空间生态修复要点，并提出面向国土空间生态修复的**人地耦合系统研究**内容。先是回顾了国土空间生态修复的演进阶段，第二论述如何科学开展国土空间生态修复，最后落脚是加强人地耦合系统研究支撑国土空间生态修复。

专家的思考高屋建瓴，高来高去，带来启迪。我结合专家论述，记录一些管理部门角度的思考，毕竟科技再支撑也需要业务部门落实具体工作。

## 一、国土空间生态修复演进阶段背后的部门机构改革

文中指出，国土空间是自然要素和人类社会要素在空间上的集成体现，且国家对国土空间优化有总要求，就是“促进生产空间集约高效、生活空间宜居适度、生态空间山清水秀”。对这“三生”空间的关系，有保护-统筹-和谐三个阶段演进过程。

保护阶段的核心目标是协调布局，发挥作用最大的是国土空间规划红线划定和严格的环保督查，就是不能过度开发，不能污染，这里主要是原国土和环保发挥作用。这一块的大规模攻坚已经差不多完成了，国土空间规划、基本农田红线、生态保护红线也都划出来了。

统筹阶段核心目标是系统治理。现在正在搞，而且从部门来说有点乱。因为系统治理必须统筹山水林田湖草，但在国家层面自然资源部和国家林草局还没完全统筹起来，就国土空间修复和国土绿化这两个词儿，内涵和工作范围都还没统一，资金调配也是处于多头管理的状态。国土绿化还是指造林，但从概念上和工作方式上都没有很好和国土空间生态修复结合起来。而按照统筹、以地域综合体为工作对象的理念的话，二者是应该有机结合的。环保部门也在积极发挥作用，比如生态环境部，最近印发了一个《[自然保护地生态环境监管工作暂行办法](http://www.mee.gov.cn/xxgk2018/xxgk/xxgk03/202012/t20201222_814322.html)》,这标志着把原来主要在生产、生活空间的工作扩展到了生态空间——这也是合理的，没道理生态空间就不需要环保了。

和谐阶段是发展目标和方向，要实现生产、生活空间有机融入生态空间之中，铸就国土生态安全格局推进绿色发展，促成人与自然和谐共生。

## 二、如何科学开展国土生态修复

原文分三部分，抄来一些。

### 以协调布局为目标，从自然地域单元的整体性出发，明确国土空间生态保护和修复的重点区域，守住自然生态安全边界

按地理和自然因素划分，大写意。根据这个划分能更好的了解地理知识。

> 2011年6月8日颁布的《全国主体功能区规划》提出了我国以“两屏三带”为主体的生态安全战略格局，即青藏高原生态屏障、黄土高原—川滇生态屏障和东北森林带、北方防沙带、南方丘陵山地带，形成了一个整体生态安全的基本轮廓。作为自然地域单元，“屏障”和“带”的区别不仅体现在空间形态上，更体现在生态系统结构和功能上。

### 以系统治理为目标，深入研究山水林田湖草沙多类自然资源要素和生态系统的相互作用关系及效应，因地制宜确定生态保护修复途径，提升生态系统质量和稳定性

> 需要意识到陆地生态系统并不是越“绿”越优。对国土空间的人工生态修复和重建应从自然地理规律出发，贯彻质量优先、稳定优先的原则，科学评判区域地带性植被的种植适宜性，在厘清自然资源要素相互作用关系及其资源环境效应的基础上，确定适于本地自然地域条件的恢复方式和山水林田湖草沙空间配置模式。

### 以人地和谐为目标，进一步将生态修复融入经济、社会、文化建设中，助力国土空间格局优化与民生福祉提升，促进经济社会发展全面绿色转型。

> 提供优质生态产品、提升区域民生福祉，是“绿水青山就是金山银山”理念下国土空间生态修复的重要使命。目前，我国国土空间生态修复通过山水林田湖草生态保护修复工程的布设，为部分区域绿色发展夯实了良好的生态本底。

## 三、加强人地耦合系统研究，支撑国土空间生态修复

看到耦合这俩字，就想起藕合来，挺好吃的。这一部分读起来，感觉有个前提是生态一不小心就退化，而且现在还差劲的很，我们需要花大气力把生态恢复到一个更加理想化的水平。

近十年这些想法可能会在论文中讨论，形成新的学术流派，有空可以掺和一把。抄一些有意思的表述。

> 需要从生态与社会耦合指标的角度，分类识别生态系统退化驱动机制，统筹明确生态修复标准体系。如果只聚焦生态系统退化过程及其空间格局，而忽视退化过程的驱动机制，则将重走“末端问题治理”的老路，不能达成“源头预防”的效果。所谓生态修复中的“源头预防”，就是要通过解耦方法，分类优化人地系统中对生态系统退化格局形成起主导作用的1个或几个自然、社会指标。在生态修复标准体系的建立中，需要对特定地域生物多样性保护、生态产品供给等多重目标统筹考虑，找到整体上对生态安全影响最大的几个指标作为重点考评对象。

> 需要从生态与社会要素耦合层次的角度，从生物地理和生态功能多个层次识别重点修复区域。在生态修复中，应同时考虑尺度的空间嵌套和属性的层次递进，因此有必要采用地理区划的方式达成对国土空间的综合认知。面向生态修复过程、生态系统服务与人类福祉级联关系的有效表征，可以采用生物地理区划、生态功能区划相**嵌套**的手段，纳入气候变化和社会经济指标作为外部变量，构建干扰导致生态系统退化程度、基于生物地理属性的生物多样性保育、基于生态系统服务的生态功能提升多层次指标体系提出区划方案。从而使识别出的国土空间生态修复重点区域，同时能够反映生态系统稳定性维持和生态产品供给等多重目标。

> 需要从生态与社会耦合效应的角度，以时空流动的视角认识生态修复下国土空间生产、生活、生态功能的区域权衡或协同。国土空间生态修复的生态和社会效应不仅是多元的、交互的，而且是时空流动的，人地耦合系统理论中的远程耦合（telecoupling）框架即通过发送系统、接收系统、溢出系统的拆分解释了这种流动性。

> 目前，远程耦合框架已被改进为全程耦合（metacoupling）框架，即在远程耦合的基础上进一步增加了邻域耦合（pericoupling）和内部耦合（intracoupling）。基于全程耦合框架下的国土空间生态修复有待在修复本地效应评价的基础上，定量识别修复过程中国土空间生产、生活、生态功能的邻域响应和远程响应，从而为生态修复绩效评估提供全面依据。

> 需要从生态与社会耦合模型的角度，发展人地系统耦合模型以预测生态修复对可持续发展的支撑。未来的人地关系研究将要进入对复杂人地系统和可持续发展系统的模拟阶段，而地理环境和人类活动两个子系统的数据匹配和路径识别依然是人地系统模拟的关键。

