---
title: 2020年说来就来了
author: 老王
date: '2020-01-15'
slug: looking-forward-to-2000
categories:
  - 随笔
tags:
  - 心情
---

## 回首和总结

2020年，工作满十年了，真快。

回首第一个十年，战略和战术上都有教训。

战略上，没有坚持**独立自主**和**积极作为**，随着手头工作和领导意志干点浮光掠影的活，对感兴趣的东西也是三天打鱼两天晒网、东一耙子西一扫帚，积极努力不够、专注探索不够，没有在这十年间耕耘的领域留下比较深的痕迹，也没有培养出比较高的专业素养。

战术上，对单位职务职称规则、同事交流合作了解不够。再具体的事情上不诉求不够清晰，合作效果不够好。

扪心自问，按自己的努力程度、天分和获得的成果，能有现在的待遇也算不错了。

当然，还有很多以更水的工作占据更好资源的人，但老这么比就没个完了。

检视自己，实事求是的说，有点对不起这十年光阴，也没体现出所在平台的价值，没有在这个平台上完成好应有的成长。

比如现在让我讲自己负责的业务，能流利生动的讲一小时不停歇吗？关键的环节，能脱稿给人讲清楚，并让人愿意听吗？推进业务，能燃起服务对象的激情吗？

确实不行。这就是，还需要进一步提高业务水平。

其他一些杂学，老觉得会点统计、R语言，可真深入吗？不抄代码的话，自己能提出什么问题，解决什么问题？工作十年，用这个东西干过什么正儿八经的活？发表过一篇论文吗？英语，能流利对话吗，能交流业务内容吗，还会写论文吗？都够呛。

**十有九年堪白眼，百无一用是书生**。

## 展望和期待

书生也有很厉害的，各个领域，各个行业都有，自怨自艾别拉人家。

年初嘛，自我批判之余畅想一下未来。

畅想未来的作用，和希望把工作交给别人干，成果自己享的心理差不多。只不过是把活儿交给未来的自己，然后现在的自己意淫一下成果的到来。

希望将来的自己能够义薄云天的把事儿扛起来，不推脱、不抱怨、**不犹疑**。

推脱抱怨容易理解，犹疑呢，是因为总容易对干的事儿的意义产生质疑。

——搞这玩意儿有啥意思呢？

这时候就需要强大的心理，不管啥事儿，先忙活起来。**只要不错，就可能有点对**。比如写论文，可能没啥用，但比起划抖音，这肯定不错，只要不错那就有点对了。当然内容要注意，三观别太乱，要是研究导师的崇高感和师娘的优美感，还不如抖音玩社会危害小呢。

希望以后的我，**以输出为抓手**，独立自主、积极作为，在项目管理、自然环境生态保护等业务方面深耕留痕，提高水平。

输出为抓手的意思就是，多写多说，多与人交流。不管是论文、材料、还是博客、随笔，不管是跟人聊天还是公开演讲，要多写多说，多与人交流。

输出的时候会有对作品的期望，期望要符合实际，时刻谨记自己的德性，不要想着能一步登天，一鸣惊人。

自己干活，基本是苦熬派。记性不好，灵性挺差，情绪不稳，写东西只能苦熬。

和情绪和解。不管是突然涌上心头的懊恼，还是忽然对未来的焦虑，还是对做了的事的不满，都要和情绪和解。

情绪是受身体影响的，身体是受基因控制的。

当然作为人有自己的主动性，但也别太为难，精神毕竟都是要基于物质的。

**时时当勉励，随心行与止**。

以一颗复杂而感恩的心，迎接工作后新十年的到来。


